#!/usr/bin/env bash
# Amazing SEO Skill — installer for full mode (L1-L4 layers).
#
# Engine package identifiers are NOT hardcoded. Set them via env vars before
# running this script. This keeps the public repo free of references to any
# specific upstream package.
#
# Required env vars:
#   DEEP_AUDIT_ENGINE_PKG          npm package name for deep-audit engine
#   DEEP_AUDIT_ENGINE_BIN_NAME     binary name installed by that package
#   AEO_CITATIONS_ENGINE_PKG_SPEC  pip install spec (PyPI name OR git+URL)
#   AEO_CITATIONS_ENGINE_BIN_NAME       binary name installed inside the venv
#   AEO_CITATIONS_ENGINE_CONFIG_FILENAME engine's expected config filename
#
# Optional:
#   AMAZING_SEO_AEO_KEYCHAIN_KEYS  comma-separated Keychain service names to
#                                  remind users about (default: standard 4)
#
# Usage:
#   DEEP_AUDIT_ENGINE_PKG=...  \
#   DEEP_AUDIT_ENGINE_BIN_NAME=...  \
#   AEO_CITATIONS_ENGINE_PKG_SPEC=...  \
#   AEO_CITATIONS_ENGINE_BIN_NAME=...  \
#   ./install.sh
set -e

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SKILL_DIR"

: "${DEEP_AUDIT_ENGINE_PKG:?must be set — see comment block at top of install.sh}"
: "${DEEP_AUDIT_ENGINE_BIN_NAME:?must be set}"
: "${AEO_CITATIONS_ENGINE_PKG_SPEC:?must be set}"
: "${AEO_CITATIONS_ENGINE_BIN_NAME:?must be set}"
: "${AEO_CITATIONS_ENGINE_CONFIG_FILENAME:?must be set — engine's expected config file name in CWD}"

echo "==> Checking prerequisites"
for cmd in python3 npm git; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "ERROR: $cmd is required but not installed" >&2
    exit 1
  fi
done

echo "    python: $(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
echo "    node:   $(node --version 2>/dev/null || echo missing)"

echo ""
echo "==> Creating Python virtualenv"
[ -d .venv ] || python3 -m venv .venv
.venv/bin/pip install --quiet --upgrade pip

echo ""
echo "==> Installing direct Python dependencies"
.venv/bin/pip install --quiet -r requirements.txt

echo ""
echo "==> Installing AEO citation engine"
.venv/bin/pip install --quiet "$AEO_CITATIONS_ENGINE_PKG_SPEC"

echo ""
echo "==> Installing Playwright browser (Chromium, ~170MB)"
.venv/bin/playwright install chromium

echo ""
echo "==> Installing deep-audit engine"
npm install -g "$DEEP_AUDIT_ENGINE_PKG"

echo ""
echo "==> Resolving engine binary paths"
DEEP_AUDIT_BIN=$(command -v "$DEEP_AUDIT_ENGINE_BIN_NAME" || echo "")
AEO_CITATIONS_BIN="$SKILL_DIR/.venv/bin/$AEO_CITATIONS_ENGINE_BIN_NAME"

if [ -z "$DEEP_AUDIT_BIN" ]; then
  NPM_PREFIX=$(npm config get prefix)
  DEEP_AUDIT_BIN="$NPM_PREFIX/bin/$DEEP_AUDIT_ENGINE_BIN_NAME"
fi

[ -x "$DEEP_AUDIT_BIN" ]    || echo "WARNING: deep-audit engine binary not found" >&2
[ -x "$AEO_CITATIONS_BIN" ] || echo "WARNING: AEO citations engine binary not found" >&2

echo ""
echo "==> Writing engine config to .bin/.engines.env (gitignored)"
cat > .bin/.engines.env <<EOF
# Auto-generated by install.sh — do not commit
AMAZING_SEO_DEEP_AUDIT_ENGINE="$DEEP_AUDIT_BIN"
AMAZING_SEO_AEO_CITATIONS_ENGINE="$AEO_CITATIONS_BIN"
AMAZING_SEO_AEO_CITATIONS_CONFIG_FILENAME="$AEO_CITATIONS_ENGINE_CONFIG_FILENAME"
EOF

echo ""
echo "==> Verifying"
"$DEEP_AUDIT_BIN" --version 2>&1 | head -1 || echo "  deep-audit: NOT WORKING"
"$AEO_CITATIONS_BIN" 2>&1 | head -1         || echo "  AEO citations: needs runtime config"
.venv/bin/python -c 'from playwright.sync_api import sync_playwright; print("  playwright: OK")'

echo ""
echo "==> Done. For multi-LLM ensemble (L4), store API keys in macOS Keychain:"
echo '    security add-generic-password -s anthropic-api-key  -a $USER -w'
echo '    security add-generic-password -s openai-api-key     -a $USER -w'
echo '    security add-generic-password -s perplexity-api-key -a $USER -w'
echo '    security add-generic-password -s x.ai-api-key       -a $USER -w'
