#!/usr/bin/env bash
# Amazing SEO Skill — one-command installer for full mode (L1-L4 layers)
# Usage: ./install.sh
set -e

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SKILL_DIR"

echo "==> Checking prerequisites"
for cmd in python3 npm git; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "ERROR: $cmd is required but not installed" >&2
    exit 1
  fi
done

PY_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
echo "    python: $PY_VER"
echo "    node:   $(node --version 2>/dev/null || echo missing)"

echo ""
echo "==> Creating Python virtualenv"
if [ ! -d .venv ]; then
  python3 -m venv .venv
fi
.venv/bin/pip install --quiet --upgrade pip

echo ""
echo "==> Installing direct Python dependencies"
.venv/bin/pip install --quiet -r requirements.txt

echo ""
echo "==> Installing AEO citation engine (Python)"
.venv/bin/pip install --quiet \
  git+https://github.com/alexpospekhov/searchstack-aeo.git

echo ""
echo "==> Installing Playwright browser (Chromium, ~170MB)"
.venv/bin/playwright install chromium

echo ""
echo "==> Installing deep-audit engine (Node)"
npm install -g @seomator/seo-audit

echo ""
echo "==> Resolving engine paths"
DEEP_AUDIT_BIN=$(command -v seomator || echo "")
AEO_CITATIONS_BIN="$SKILL_DIR/.venv/bin/searchstack"

if [ -z "$DEEP_AUDIT_BIN" ]; then
  # npm prefix may not be on PATH; probe known location
  NPM_PREFIX=$(npm config get prefix)
  DEEP_AUDIT_BIN="$NPM_PREFIX/bin/seomator"
fi

if [ ! -x "$DEEP_AUDIT_BIN" ]; then
  echo "WARNING: deep-audit engine not found after install" >&2
fi
if [ ! -x "$AEO_CITATIONS_BIN" ]; then
  echo "WARNING: AEO citation engine not found after install" >&2
fi

echo ""
echo "==> Writing engine config to .bin/.engines.env"
cat > .bin/.engines.env <<EOF
# Auto-generated by install.sh — do not commit
AMAZING_SEO_DEEP_AUDIT_ENGINE="$DEEP_AUDIT_BIN"
AMAZING_SEO_AEO_CITATIONS_ENGINE="$AEO_CITATIONS_BIN"
EOF

echo ""
echo "==> Verifying"
"$DEEP_AUDIT_BIN" --version 2>&1 | head -1 || echo "  deep-audit: NOT WORKING"
"$AEO_CITATIONS_BIN" 2>&1 | head -1 || echo "  AEO citations: NOT WORKING (config needed)"
.venv/bin/python -c 'from playwright.sync_api import sync_playwright; print("  playwright: OK")'

echo ""
echo "==> Done. For multi-LLM ensemble, store API keys in macOS Keychain:"
echo '    security add-generic-password -s anthropic-api-key   -a $USER -w'
echo '    security add-generic-password -s openai-api-key      -a $USER -w'
echo '    security add-generic-password -s perplexity-api-key  -a $USER -w'
echo '    security add-generic-password -s x.ai-api-key        -a $USER -w'
